# (C) Copyright IBM Corporation 2022,2023
swagger: '2.0'
info:
  version: 1.0.0
  title: Order
  x-ibm-name: ibm-sample-order-api
  description: View and track your orders and deliveries.
  termsOfService: 'This API is provided as a sample with no associated guarantees.  '
  contact:
    name: IBM Corporation
    url: https://www.ibm.com/products/api-connect
basePath: /order
x-ibm-configuration:
  properties:
    target-url:
      value: >-
        https://sample-api.us-east-a.apiconnect.automation.ibm.com/orders/order/{orderNumber}
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
 
  assembly:
  execute:
    - invoke:
        title: order lookup
        version: 2.0.0
        verb: keep
        target-url: $(target-url)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
          values: []
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        persistent-connection: true
        backend-type: json
        output:
          order:
            description: Retrieves order data from the fulfillment system using the key of the provided order number.
    - parse:
        version: 2.1.0
        title: parse response
        parse-settings-reference:
          default: apic-default-parsesettings
        input: order
        output:
          order:
            description: Parse the JSON from the order fulfillment system so that the values can be used later in the flow.
    - map:
        version: 2.0.0
        title: map input to lambda
        inputs:
          input:
            schema:
              type: object
              properties:
                delivery_method:
                  type: string
                  name: delivery_method
                tracking_reference:
                  type: string
                  name: tracking_reference
        variable: order.body
        outputs:
          output:
            schema:
              type: object
              properties:
                shipper:
                  type: string
                  name: shipper
                reference:
                  type: string
                  name: reference
        content: application/json
        actions:
          - set:
              output.shipper: input.delivery_method
          - set:
              output.reference: input.tracking_reference
              
     - xslt:
        source: response.body
        style: |
        <xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
            <xsl:template match="/">
              <root>
                <order>
                  <order_number><xsl:value-of select="order_number"/></order_number>
                  <tracking_status><xsl:value-of select="tracking_status"/></tracking_status>
                  <shipped_at><xsl:value-of select="shipped_at"/></shipped_at>
                  <created_at><xsl:value-of select="created_at"/></created_at>
                  <status><xsl:value-of select="status"/></status>
                  <tracking_reference><xsl:value-of select="tracking_reference"/></tracking_reference>
                </order>
              </root>
            </xsl:template>
          </xsl:stylesheet>
        target: response.body
  policies:
    - set:
        actions:
          - set-variable:
              name: shipper
              value: request.queryparam.delivery_method
        continueOnError: false
        enabled: true
        name: Set shipper variable
        displayName: Set shipper variable
    - set:
        actions:
          - set-variable:
              name: reference
              value: request.queryparam.tracking_reference
        continueOnError: false
        enabled: true
        name: Set reference variable
        displayName: Set reference variable
    - set:
        actions:
          - set-variable:
              name: response.body.order_number
              value: request.queryparam.orderNumber
          - set-variable:
              name: response.body.tracking_status
              value: request.queryparam.tracking_status
          - set-variable:
              name: response.body.shipped_at
              value: request.queryparam.shipped_at
          - set-variable:
              name: response.body.created_at
              value: request.queryparam.created_at
          - set-variable:
              name: response.body.status
              value: request.queryparam.status
          - set-variable:
              name: response.body.tracking_reference
              value: request.queryparam.tracking_reference
        continueOnError: false
        enabled: true
        name: Set output variables for order details
        displayName: Set output variables for order details
paths:
  /{orderNumber}:
    parameters:
      - name: orderNumber
        required: true
        in: path
        type: string
        description: Order number to lookup - you should find this in your confirmation e-mail
    get:
      responses:
        '200':
          description: Order found successfully
          schema:
            type: object
            title: Order Details
            properties:
              order_number:
                title: Order Number
                type: string
                example: ORD00989792
              tracking_status:
                title: Tracking Status
                type: object
              shipped_at:
                title: Date Shipped
                type: string
                format: date-time
              created_at:
                title: Date Order Created
                type: string
                format: date-time
              status:
                title: Order Status
                type: string
                enum:
                  - SHIPPED
                  - PICKED
                  - PENDING
                  - DELIVERED
              tracking_reference:
                title: Tracking Reference
                type: string
          summary: Retrieve the details of your order.
          produces:
            - application/json
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
externalDocs:
url: https://github.com/ibm-apiconnect/sample-orders-api
  description: Github project for this API, containing source code and deployment pipeline
