swagger: '2.0'
info:
  version: 1.0.0
  title: test-api
  x-ibm-name: test-api
basePath: /test-api
x-ibm-configuration:
  properties:
    target-url:
      value: https://httpbin.org/get
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - ratelimit:
          version: 2.2.0
          title: ratelimit
          source: plan-default
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: https://httpbin.org/get
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: allowlist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
          persistent-connection: true
      - parse:
          version: 2.1.0
          title: parse
          parse-settings-reference:
            default: apic-default-parsesettings
      - json-to-xml:
          version: 2.0.0
          title: json-to-xml
          root-element-name: json
          always-output-root-element: false
          unnamed-element-name: element
      - xslt:
          version: 1.0.0
          title: xslt
          input: true
          source: >-
            <xsl:stylesheet version="1.0"
            xmlns:xsl="http://www.w3.org/1999/XSL/Transform">      <xsl:template
            match="/">        <Hello>World!</Hello>      </xsl:template>   
            </xsl:stylesheet>
    finally: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
  /get: {}
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
  - application/xml
